# Generated by Django 5.0.4 on 2024-05-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPurchaseOrder', '0002_alter_purchaseorder_po_number_performancemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceModel',
        ),
    ]
