# Generated by Django 5.0.4 on 2024-05-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPerformanceModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
