# Generated by Django 5.0.4 on 2024-05-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPerformanceModel', '0002_alter_performancemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemodel',
            name='date',
            field=models.DateField(),
        ),
    ]
